name = "Metaanal"
uuid = "e76faee6-a611-437b-b93f-bebfb2044dfd"
authors = ["Arindam Basu"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
